### ISSUE TITLE
[주문관리 통합/ 프론트엔드] 메인페이지 제작 및 기능 연결

### ISSUE THREAD

**Issue by DISNOTACAT** [ssg-240304-java2/shop-techmya#61]
### 메인페이지 통합
- [x] Admin 메인페이지
- [x] Shop 메인페이지
- [x] Shop-Admin 연결 버튼 연결 (로그인/로그아웃)
- [ ] 각 기능별 새페이지 연결

### 프로젝트
- [x] 프로젝트 패키지 정리

**Comment by l2chmnl** [comment]
각 페이지에서 board 클릭하면 메인에서 클릭한 서브 메뉴명과 다른 문제 해결 완료
각 페이지에서 board 서브 메뉴 들어가면 메인에서 들어가는 결과와 다른 문제 수정 해결 완료(게시글 목록 보이냐 안보이냐 차이)
